### PR TITLE
Add Postgres as chart dependency

### PR DESCRIPTION
**Pull request by tklein**
- allow configuration of Postgres via chart dependency

### CODE REVIEW

**Comment by halkeye** [comment]
so I have one centralized postgres server I use for all my projects. I've never used the dependants and usually disable them when they come up in other helm charts.

What advantage does coupling it to its own postgres install have?

**Comment by tklein** [comment]
I don't have any postgres server running so far (using mariadb usually), so I'd need to use a different helm chart to install a postgres with its own values.yaml file. So the idea is to offer the option to install everything that is needed to run synapse with this chart.

More generally speaking, for testing purposes, when you want to start from scratch every time, it's it's a lot easier to clean up if you have one DB instance for every deployment.

**Comment by halkeye** [comment]
I've never used this functionality before. Do i need to update my chart building at all to use the helm dependancies commands?

**Comment by halkeye** [comment]
I'm usually reluctant to import features I'll never use, just because I might break it, but this is just the enabled flag, so it should be fine.

Can you update the changelog annotation at the bottom of Chart.yaml as well?

**Comment by varac** [comment]
@tklein Did you notice above comments from @halkeye ?

**Comment by tklein** [comment]
@varac Totally missed that somehow. Will resolve the conflict and update the changelog

**Comment by halkeye** [comment]
doesn't seem to break my install, so sounds good to me.

**Comment by varac** [comment]
@halkeye great! How are the charts build ? Looking at https://github.com/halkeye/helm-charts/tree/gh-pages/synapse I see the latest version is still 0.7.45.

**Comment by halkeye** [comment]
Oh weird i'm no longer getting emails when things fail. Jenkins should be updating the commit status so you should be able to see the X above

https://ci.g4v.dev/job/halkeye-helm-charts/job/synapse/job/master/3/console

looks like helm package doesn't work right with dependancy charts? I'll see if i have time to look into it this weekend

**Comment by varac** [comment]
> looks like helm package doesn't work right with dependancy charts? 

You're just missing an extra `helm dependency update` step:

```
❯ helm package .      
Error: found in Chart.yaml, but missing in charts/ directory: postgresql

❯ helm dependency list
NAME      	VERSION 	REPOSITORY                        	STATUS 
postgresql	~10.3.17	https://charts.bitnami.com/bitnami	missing

❯ helm dependency update
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.bitnami.com/bitnami" chart repository
Hang tight while we grab the latest from your chart repositories...
...
Update Complete. ⎈Happy Helming!⎈
Saving 1 charts
Downloading postgresql from repo https://charts.bitnami.com/bitnami
Deleting outdated charts

❯ ls -al charts 
total 56
drwxr-xr-x 2 varac varac  4096 Sep  2 22:02 .
drwxr-xr-x 5 varac varac  4096 Sep  2 22:02 ..
-rw-r--r-- 1 varac varac 48323 Sep  2 22:02 postgresql-10.3.18.tgz

❯ helm package .
Successfully packaged chart and saved it to: /home/varac/kubernetes/charts/halkeye-helm-charts/synapse/synapse-0.7.47.tgz
```

**Comment by varac** [comment]
Oh, and you should check in the `Chart.lock` and gitignore the `charts/` directory, which are both added by `helm dependency update`.

**Comment by halkeye** [comment]
Oh it's not something I should run every build. But once every time I update deps?

Either way I broke ldapnso i can't get into Jenkins toll after work..I think

**Comment by halkeye** [comment]
Okay I just did it the easy way, so the lock is committed in this repo, and a new release is out.

**Pull request merged**
