### PR TITLE
Expose metrics port 9000 to service if metrics_enabled

### LINKED ISSUE #8: How to enable metrics ?
I need help enabling prometheus metrics. I see `enable_metrics` in values.yaml but it's not referenced in any template.
I also see the metrics port 9000 in `homeserver.listeners`, but it's also not used, only the first entry is used in these templates: 

```
❯ grep listeners -ir                            
values.yaml:  # if 'webclient' is configured under the 'listeners' configuration.
values.yaml:  listeners:
values.yaml:  # 'listeners', in particular 'template_dir' and 'version'.
values.yaml:  worker_listeners:
values.yaml:  worker_listeners:
templates/deployment_federation_reader.yaml:              containerPort: {{ (index .Values.federation_reader.worker_listeners 0).port }}
templates/deployment_federation_sender.yaml:              containerPort: {{ (index .Values.federation_sender.worker_listeners 0).port }}
```

When I exec into the synapse pod, I can get metrics with `curl localhost:9000`, but I can't reach this port from outside the pod.

@halkeye  Do you use synapse metrics, and how ?

### PR DESCRIPTION
**Pull request by varac**
Fixes: #8

### CODE REVIEW

**Comment by varac** [comment]
I tried this branch and I can confirm it works now!

**Comment by halkeye** [comment]
Can you update chart.yaml?

**Comment by varac** [comment]
Done!

**Comment by halkeye** [comment]
ty

**Pull request merged**
